# Matrix Math

## Inner Product and Outer Product
Youtube tutorial:
https://www.youtube.com/watch?v=FCmH4MqbFGs

Matrix algebra in python cheatsheet:
https://www.tutorialspoint.com/matrix-manipulation-in-python

### Inner Product
Inner product is the same as dot product

For matrices:

In [23]:
import numpy as np
u = np.array([[1, 3, 2]])
v = np.array([[2, 4, 6]])
print("u = ")
print(u)
print("v = ")
print(v)

u = 
[[1 3 2]]
v = 
[[2 4 6]]


Inner product is $u^{T}v$

In [40]:
print("u.T = ", u.T)
print("v = ")
print(v)
iProd = np.multiply(u, v.T)
print("iProd =")
print(iProd)


u.T =  [[1]
 [3]
 [2]]
v = 
[[2 4 6]]
iProd =
[[ 2  6  4]
 [ 4 12  8]
 [ 6 18 12]]


Turns out numpy mupltiply does an element-wise multiply. `np.dot()` can be used to do a dot product of arrays with the same dimensions.
For other workarounds, see https://stackoverflow.com/questions/21562986/numpy-matrix-vector-multiplication